# Feature Engineering

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/cleaned_data.csv")

df.head()

,LOG_ID,MRN,SMRTDTA_ELEM_VALUE,AGE,HEIGHT,WEIGHT,SEX,AN_START_DATETIME,Lab Code,Lab Name,Observation Value,Measurement Units,Collection Datetime
0,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,1988-5,C reactive protein,7.6,MG/DL,2021-08-31 05:44:00
1,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,2028-9,Carbon dioxide,23.0,mmol/L,2021-09-02 06:30:00
2,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,2345-7,Glucose,119.0,mg/dL,2021-09-02 06:30:00
3,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,20570-8,Hematocrit,27.8,%,2021-09-01 07:50:00
4,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,30350-3,Hemoglobin,9.2,G/DL,2021-09-01 07:50:00

### (1) Create the binary response variable from SMRTDTA_ELEM_VALUE

In [3]:
df["hypoxemia"] = (
    df["SMRTDTA_ELEM_VALUE"]
    .str.lower()
    .str.contains("hypoxemia", na=False)
    .astype(int)
)

df.head()

,LOG_ID,MRN,SMRTDTA_ELEM_VALUE,AGE,HEIGHT,WEIGHT,SEX,AN_START_DATETIME,Lab Code,Lab Name,Observation Value,Measurement Units,Collection Datetime,hypoxemia
0,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,1988-5,C reactive protein,7.6,MG/DL,2021-08-31 05:44:00,0
1,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,2028-9,Carbon dioxide,23.0,mmol/L,2021-09-02 06:30:00,0
2,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,2345-7,Glucose,119.0,mg/dL,2021-09-02 06:30:00,0
3,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,20570-8,Hematocrit,27.8,%,2021-09-01 07:50:00,0
4,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,30350-3,Hemoglobin,9.2,G/DL,2021-09-01 07:50:00,0

### (2) Calculate BMI

In [4]:
df["bmi"] = df["WEIGHT"] / (df["HEIGHT"] ** 2)

df.head()

,LOG_ID,MRN,SMRTDTA_ELEM_VALUE,AGE,HEIGHT,WEIGHT,SEX,AN_START_DATETIME,Lab Code,Lab Name,Observation Value,Measurement Units,Collection Datetime,hypoxemia,bmi
0,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,1988-5,C reactive protein,7.6,MG/DL,2021-08-31 05:44:00,0,24.170546
1,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,2028-9,Carbon dioxide,23.0,mmol/L,2021-09-02 06:30:00,0,24.170546
2,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,2345-7,Glucose,119.0,mg/dL,2021-09-02 06:30:00,0,24.170546
3,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,20570-8,Hematocrit,27.8,%,2021-09-01 07:50:00,0,24.170546
4,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,30350-3,Hemoglobin,9.2,G/DL,2021-09-01 07:50:00,0,24.170546

### (3) Convert SEX to binary (0 for male and 1 for female)

In [5]:
df["sex"] = df["SEX"].map({"Male": 1, "Female": 0})
df.head()

,LOG_ID,MRN,SMRTDTA_ELEM_VALUE,AGE,HEIGHT,WEIGHT,SEX,AN_START_DATETIME,Lab Code,Lab Name,Observation Value,Measurement Units,Collection Datetime,hypoxemia,bmi,sex
0,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,1988-5,C reactive protein,7.6,MG/DL,2021-08-31 05:44:00,0,24.170546,1
1,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,2028-9,Carbon dioxide,23.0,mmol/L,2021-09-02 06:30:00,0,24.170546,1
2,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,2345-7,Glucose,119.0,mg/dL,2021-09-02 06:30:00,0,24.170546,1
3,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,20570-8,Hematocrit,27.8,%,2021-09-01 07:50:00,0,24.170546,1
4,0004678c0906bb9e,6b03d87f76b29311,NaN,70,1.651,65.884098,Male,2021-09-02 11:32:00,30350-3,Hemoglobin,9.2,G/DL,2021-09-01 07:50:00,0,24.170546,1

In [6]:
df.to_csv("data/feature_engineered_data.csv", index=False)