In [2]:
import pandas as pd

## Load Data

Documentation: https://mover.ics.uci.edu/documentation.html

### Data files

- `patient_information`:
    1. demographic information including age, sex, height, and weight,
    2. information regarding the surgery being performed including: the type of surgery, the start and end time of both the surgery and anesthesia, ASA status, and discharge disposition.


- `patient_labs`: labs ordered for a patient, the corresponding observed measurements, and the reference measurements for each lab.

- `patient_procedure events`: preoperative, perioperative, and postoperative procedural events and the corresponding time of the event.

- `patient_post_op_complications`: the type of complication, when the complication was observed, and a free text note field outlining more specific details

Merge by `MRN` and `LOG_ID`.

In [3]:
# load data
pat_info = pd.read_csv("Data/patient_information.csv")
pat_labs = pd.read_csv("Data/patient_labs.csv")
pat_procedure = pd.read_csv("Data/patient_procedure events.csv")
pat_postop = pd.read_csv("Data/patient_post_op_complications.csv")

## Postoperative complications

#### Variables to use
The **outcome** of interest is postoperative hypoxemia, which is recorded in `SMRTDTA_ELEM_VALUE`.

#### Wrangling procedures
`SMRTDTA_ELEM_VALUE` is a free text column, need to trasform into a *binary* target column:
1. Convert to all to lower case
2. Positive outcome (hpyoxemia): cells containing the keyword "hypoxemia"
3. Negative outcome (no hypoxemia): all other complications
    - Include NAs in `SMRTDTA_ELEM_VALUE` (which should represent no complication)

In [4]:
pat_postop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203945 entries, 0 to 203944
Data columns (total 6 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   LOG_ID              203945 non-null  object
 1   MRN                 203945 non-null  object
 2   Element_Name        203945 non-null  object
 3   CONTEXT_NAME        203945 non-null  object
 4   Element_abbr        203945 non-null  object
 5   SMRTDTA_ELEM_VALUE  6741 non-null    object
dtypes: object(6)
memory usage: 9.3+ MB

In [5]:
pat_postop.head()

,LOG_ID,MRN,Element_Name,CONTEXT_NAME,Element_abbr,SMRTDTA_ELEM_VALUE
0,b00c588406aae5cc,1a42f0bed60c5598,AN AQI POST-OP COMPLICATIONS,ENCOUNTER,AN Post-op Complications,NaN
1,a16571d21874c0a7,596a6dc60f54a0bb,AN AQI POST-OP COMPLICATIONS,NOTE,AN Post-op Complications,NaN
2,a16571d21874c0a7,596a6dc60f54a0bb,AN AQI POST-OP COMPLICATIONS,NOTE,AN Post-op Complications,NaN
3,1d9ff2d157fa4c86,60e6ea6cf06b58d7,AN AQI POST-OP COMPLICATIONS,ORDER,AN Post-op Complications,NaN
4,2ae43a4a39735956,59c5483e0654e105,AN AQI POST-OP COMPLICATIONS,ENCOUNTER,AN Post-op Complications,Other

## Patient information

#### Variables to use

- `BIRTH_DATE`: patients' age in years.
- `SEX`: genotypical sex of the patients.
- `HEIGHT`: height in feet and inches (ex. 5'6).
- `WEIGHT`: weight in ounces.
- `AN_START_DATETIME`, `AN_STOP_DATETIME`: date and time at which anesthesia was started / stopped.

#### Wrangling procedures

**Rename** `BIRTH_DATE` to `AGE` for clarity.

**Unit / type Conversion**

1. Convert `HEIGHT` into centimeters so the colum is numeric.
    - Use `df['HEIGHT'].str.split("'", expand=TRUE).astype(float)` to split `HEIGHT` into two columns (feet and inches, `expand=True` creates a separate df for this).
    - Conversion formula $\text{height in cm} = ((\text{feet} \times 12) + \text{inches}) \times 2.54$
2. (Optional) Convert `WEIGHT` into kg (or grams) for consistency.
    - $\text{weight in kg} = \text{ounces} \times 0.0283495$
3. Convert `AN_START_DATETIME` and `AN_STOP_DATETIME` to `datetime`.

**Handle missing values**
1. No missings for `BIRTH_DATE` and `SEX`.
2. Missing values in `HEIGHT` and `WEIGHT` could be imputed (ex. by regression imputation using other demographic features as predictors).

In [6]:
pat_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65728 entries, 0 to 65727
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   LOG_ID                65728 non-null  object
 1   MRN                   65728 non-null  object
 2   DISCH_DISP_C          65721 non-null  float64
 3   DISCH_DISP            65721 non-null  object
 4   HOSP_ADMSN_TIME       65728 non-null  object
 5   HOSP_DISCH_TIME       65714 non-null  object
 6   LOS                   65714 non-null  float64
 7   ICU_ADMIN_FLAG        65728 non-null  object
 8   SURGERY_DATE          65728 non-null  object
 9   BIRTH_DATE            65728 non-null  int64
 10  HEIGHT                52695 non-null  object
 11  WEIGHT                63319 non-null  float64
 12  SEX                   65728 non-null  object
 13  PRIMARY_ANES_TYPE_NM  65168 non-null  object
 14  ASA_RATING_C          58758 non-null  float64
 15  ASA_RATING            58758 non-null  object
 16  PATIENT_CLASS_GROUP   65728 non-null  object
 17  PATIENT_CLASS_NM      65728 non-null  object
 18  PRIMARY_PROCEDURE_NM  65722 non-null  object
 19  IN_OR_DTTM            59170 non-null  object
 20  OUT_OR_DTTM           59102 non-null  object
 21  AN_START_DATETIME     58244 non-null  object
 22  AN_STOP_DATETIME      58230 non-null  object
dtypes: float64(4), int64(1), object(18)
memory usage: 11.5+ MB

In [13]:
pat_info[pat_info["MRN"]=="f51067c20a867fc0"]

,LOG_ID,MRN,DISCH_DISP_C,DISCH_DISP,HOSP_ADMSN_TIME,HOSP_DISCH_TIME,LOS,ICU_ADMIN_FLAG,SURGERY_DATE,BIRTH_DATE,...,PRIMARY_ANES_TYPE_NM,ASA_RATING_C,ASA_RATING,PATIENT_CLASS_GROUP,PATIENT_CLASS_NM,PRIMARY_PROCEDURE_NM,IN_OR_DTTM,OUT_OR_DTTM,AN_START_DATETIME,AN_STOP_DATETIME
26120,0c0a44b0e5e15483,f51067c20a867fc0,15.0,Home Routine,11/19/17 11:11,1/7/18 17:24,49.0,Yes,12/3/17 0:00,90,...,NaN,NaN,NaN,Inpatient,Inpatient Admission,"LAPAROTOMY, EXPLORATORY",NaN,NaN,NaN,NaN

In [6]:
cols_of_interest = ["LOG_ID", "MRN", "BIRTH_DATE", "SEX", "HEIGHT", "WEIGHT", 
                    "AN_START_DATETIME", "AN_STOP_DATETIME"]
pat_demo = pat_info[cols_of_interest]
pat_demo.head()

,LOG_ID,MRN,BIRTH_DATE,SEX,HEIGHT,WEIGHT,AN_START_DATETIME,AN_STOP_DATETIME
0,cd1636c6279d73a0,2e92522a5f2a2a22,47,Female,NaN,2832.47,12/20/18 12:27,12/20/18 17:34
1,fc53c06ee2cfe438,b7a91e623d957d8f,81,Male,5' 6,2515.01,9/27/19 9:52,9/27/19 11:44
2,2f0090c47da34608,b68d6c7198f30f73,49,Female,NaN,1964.74,4/8/19 14:41,4/8/19 18:53
3,6d3b621880c6ced4,46aa48e89b9c50e8,54,Female,5' 3,2638.47,12/3/18 8:09,12/3/18 11:52
4,82f89e10f2855420,c2756216cc89b795,44,Female,NaN,1880.08,4/19/19 8:14,4/19/19 15:00

In [7]:
pat_demo['HEIGHT'].str.split("'", expand=True).astype(float)

         0    1
0      NaN  NaN
1      5.0  6.0
2      NaN  NaN
3      5.0  3.0
4      NaN  NaN
...    ...  ...
65723  5.0  9.0
65724  5.0  3.0
65725  NaN  NaN
65726  5.0  4.0
65727  NaN  NaN

[65728 rows x 2 columns]

### Check missingness in `HEIGHT` and `WEIGHT`

In [8]:
pat_info.sort_values(by = "BIRTH_DATE")

,LOG_ID,MRN,DISCH_DISP_C,DISCH_DISP,HOSP_ADMSN_TIME,HOSP_DISCH_TIME,LOS,ICU_ADMIN_FLAG,SURGERY_DATE,BIRTH_DATE,...,PRIMARY_ANES_TYPE_NM,ASA_RATING_C,ASA_RATING,PATIENT_CLASS_GROUP,PATIENT_CLASS_NM,PRIMARY_PROCEDURE_NM,IN_OR_DTTM,OUT_OR_DTTM,AN_START_DATETIME,AN_STOP_DATETIME
19701,a56d6b512089de6a,82c0085530e66023,30.0,Long Term Care Facility,3/21/20 2:28,4/20/20 17:48,30.0,Yes,3/29/20 0:00,17,...,General,4.0,Incapacitating Disease,Inpatient,Inpatient Admission,"ORIF, FRACTURE, MANDIBLE, WITH MAXILLOMANDIBUL...",3/29/20 16:59,3/29/20 19:25,3/29/20 16:59,3/29/20 19:39
30969,61d748e02b7d87ba,68ff882f087fe113,4.0,Rehab Facility (not this hospital),8/21/22 23:37,9/12/22 18:36,22.0,Yes,9/5/22 0:00,17,...,General,3.0,Severe Systemic Disease,Inpatient,Inpatient Admission,VIDEO-ASSISTED THORACOSCOPIC SURGERY (VATS),9/5/22 17:22,9/5/22 19:49,9/5/22 17:22,9/5/22 20:06
4474,ca9f7bec2e448c4f,d10daf32d9890d80,15.0,Home Routine,8/24/19 9:15,8/24/19 17:26,0.0,No,8/24/19 0:00,17,...,General,2.0,Mild Systemic Disease,Outpatient,Hospital Outpatient Surgery,"ORIF, FRACTURE, FEMUR",8/24/19 13:42,8/24/19 15:45,8/24/19 13:42,8/24/19 15:54
30521,a4e1d171afa6c5bf,d3072e303408be01,15.0,Home Routine,6/4/21 10:34,6/5/21 10:45,1.0,Yes,6/4/21 0:00,17,...,General,1.0,Healthy,Outpatient,Hospital Outpatient Surgery,"REPAIR, STENOSIS, NOSE, VESTIBULE",6/4/21 12:07,6/4/21 18:18,6/4/21 12:11,6/4/21 18:16
39591,826d4a0121f3fb7b,ca6d04375d96ed75,15.0,Home Routine,9/23/20 20:04,10/3/20 18:20,10.0,Yes,10/2/20 0:00,17,...,General,2.0,Mild Systemic Disease,Inpatient,Inpatient Admission,"ARTHROSCOPY, KNEE",10/2/20 16:18,10/2/20 18:38,10/2/20 16:20,10/2/20 18:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21966,ddbaf380803948cc,885483578e85eee4,15.0,Home Routine,8/11/20 6:28,8/11/20 16:38,0.0,No,8/11/20 0:00,90,...,General,3.0,Severe Systemic Disease,Outpatient,Hospital Outpatient Surgery,"BLEPHAROPLASTY, FOR BLEPHAROPTOSIS, WITH CANTH...",8/11/20 8:09,8/11/20 13:12,8/11/20 8:10,8/11/20 13:20
20877,278ca303cf8f799c,3f633da6aa9bb1f6,6.0,Skilled Nursing Facility,11/23/20 14:00,12/10/20 20:03,17.0,Yes,11/28/20 0:00,90,...,Regional,3.0,Severe Systemic Disease,Inpatient,Inpatient Admission,"AMPUTATION, FOOT",NaN,NaN,NaN,NaN
38746,9f8e05355cb9f426,4fe496b1c23ca55b,15.0,Home Routine,1/26/22 8:03,1/26/22 15:49,0.0,No,1/26/22 0:00,90,...,Moderate Sedation - by non-anesthesia staff only,NaN,NaN,Outpatient,Hospital Outpatient Surgery,"CATHETERIZATION, HEART, LEFT, WITH INTERVENTIO...",NaN,NaN,NaN,NaN
14876,0fd82f387416ef64,326efc01e88ec344,6.0,Skilled Nursing Facility,7/24/20 11:39,7/28/20 19:05,4.0,No,7/27/20 0:00,90,...,Monitored Anesthesia Care (MAC),3.0,Severe Systemic Disease,Inpatient,Inpatient Admission,"COLONOSCOPY, WITH BIOPSY",NaN,NaN,NaN,NaN
61912,7b4cb0e498d19946,ceb815e965340d25,6.0,Skilled Nursing Facility,10/17/20 6:26,10/23/20 17:14,6.0,Yes,10/17/20 0:00,90,...,General,3.0,Severe Systemic Disease,Inpatient,Hospital Inpatient Surgery,"CONVERSION, PREVIOUS HIP SURGERY TO TOTAL HIP ...",10/17/20 8:19,10/17/20 15:05,10/17/20 8:19,10/17/20 15:25

## Labs

#### Variables to use

- `Lab Code`: Logical Observation Identifier Names and Codes (LOINC) code for the laboratory test.
- `Lab Name`: long common name for the laboratory test.
- `Observation Value`: observed value for the lab.
- `Measurement Units`: units associated with observed value.
- `Collection Datetime`: date and time at which the lab was taken.
    - Used to related lab measurements to `EVENT_TIME` in the `patient procedure events` data.
 
#### Wrangling procedures
**Unit / type Conversion**
1. Convert `Collection Datetime` to `datetime`.

In [9]:
pat_labs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29079344 entries, 0 to 29079343
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   LOG_ID               object
 1   MRN                  object
 2   ENC_TYPE_NM          object
 3   Lab Code             object
 4   Lab Name             object
 5   Observation Value    float64
 6   Measurement Units    object
 7   Reference Range      object
 8   Abnormal Flag        object
 9   Collection Datetime  object
dtypes: float64(1), object(9)
memory usage: 2.2+ GB

In [25]:
pat_labs[["LOG_ID", "MRN"]].value_counts().size

56127

In [10]:
pat_labs.head()

,LOG_ID,MRN,ENC_TYPE_NM,Lab Code,Lab Name,Observation Value,Measurement Units,Reference Range,Abnormal Flag,Collection Datetime
0,0da0bc3be9423462,1bb09d5761661c7d,Hospital Encounter,11475-1,Microorganism identified,9999999.0,Unknown,Unknown,N,2021-01-14 20:58:00
1,0da0bc3be9423462,1bb09d5761661c7d,Hospital Encounter,1975-2,Bilirubin,1.4,mg/dL,0.0-1.4,N,2021-01-13 10:41:00
2,3ab8e6344cc9f954,559c869f9d7db8ee,Hospital Encounter,19235-1,Base excess^^standard,9999999.0,MMOL/L,Unknown,N,2020-03-08 00:40:00
3,3ab8e6344cc9f954,559c869f9d7db8ee,Hospital Encounter,19235-1,Base excess^^standard,9999999.0,MMOL/L,Unknown,N,2020-03-10 13:30:00
4,3ab8e6344cc9f954,559c869f9d7db8ee,Hospital Encounter,1959-6,Bicarbonate,20.0,MMOL/L,21-27,L,2020-03-07 23:33:00

In [26]:
pat_labs[["LOG_ID", "MRN"]].value_counts().size

56127

In [11]:
pat_labs[pat_labs["Lab Name"].str.contains("Leuko")]

,LOG_ID,MRN,ENC_TYPE_NM,Lab Code,Lab Name,Observation Value,Measurement Units,Reference Range,Abnormal Flag,Collection Datetime
75,3ab8e6344cc9f954,559c869f9d7db8ee,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,7.9,THOUS/MCL,4.0-10.5,N,2020-03-08 04:09:00
76,3ab8e6344cc9f954,559c869f9d7db8ee,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,8.2,THOUS/MCL,4.0-10.5,N,2020-03-10 04:13:00
77,3ab8e6344cc9f954,559c869f9d7db8ee,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,8.7,THOUS/MCL,4.0-10.5,N,2020-03-12 03:27:00
79,3ab8e6344cc9f954,559c869f9d7db8ee,Hospital Encounter,46702-7,Leukocytes,3.0,#/HPF,0-5,N,2020-03-09 16:11:00
129,389f1756fb0b686f,484886fae660b70b,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,2.9,THOUS/MCL,4.0-10.5,L,2020-06-24 07:37:00
...,...,...,...,...,...,...,...,...,...,...
29079315,e1689815e6ed5bfa,f37bfcd358d39f2c,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,5.5,THOUS/MCL,4.0-10.5,N,2020-08-24 06:46:00
29079316,e1689815e6ed5bfa,f37bfcd358d39f2c,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,6.3,THOUS/MCL,4.0-10.5,N,2020-08-26 08:15:00
29079317,e1689815e6ed5bfa,f37bfcd358d39f2c,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,8.5,THOUS/MCL,4.0-10.5,N,2020-08-15 07:40:00
29079318,e1689815e6ed5bfa,f37bfcd358d39f2c,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,11.4,THOUS/MCL,4.0-10.5,H,2020-08-13 04:33:00
29079319,e1689815e6ed5bfa,f37bfcd358d39f2c,Hospital Encounter,33256-9,Leukocytes^^corrected for nucleated erythrocytes,17.1,THOUS/MCL,4.0-10.5,H,2020-08-12 10:56:00

## Procedure events

#### Variables to use
- `EVENT_DISPLAY_NAME`: name of the anesthesia event.
- `EVENT_TIME`: date and time at which the event occurred.

#### Wrangling procedure
1. Convert `EVENT_TIME` to `datetime`.

In [12]:
pat_procedure.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640223 entries, 0 to 640222
Data columns (total 5 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   LOG_ID              640223 non-null  object
 1   MRN                 640223 non-null  object
 2   EVENT_DISPLAY_NAME  640223 non-null  object
 3   EVENT_TIME          640223 non-null  object
 4   NOTE_TEXT           210 non-null     object
dtypes: object(5)
memory usage: 24.4+ MB

In [15]:
pat_procedure.head(5)

,LOG_ID,MRN,EVENT_DISPLAY_NAME,EVENT_TIME,NOTE_TEXT
0,a739a81fc152e77c,3936fad285669edf,"Transported to PACU/ICU with O2, vital signs s...",8/9/19 11:47,NaN
1,a6494a6557e211ff,3b095ccb1c4f124f,Two Anti-Emetics Administered,6/17/19 11:54,NaN
2,a6494a6557e211ff,3b095ccb1c4f124f,Two Anti-Emetics Administered,6/17/19 11:54,NaN
3,e1a066d449ed18b0,499386c1a8693fd0,Sign In,4/27/19 0:38,NaN
4,e1a066d449ed18b0,499386c1a8693fd0,Quick Note,4/27/19 3:04,NaN

## Data Merging

To answer the RQ, the final dataset needs to have the following variables:

- **Outcome**: binary indicator of postoperative hypoxemia (0 = no, 1 = yes)

- **Predictors**:

    - Demographic variables: BMI, sex and age
    - Latest available preoperative lab test results (time stamp, lab name and measurement (with units)), where we use the latest lab test results before the start of anesthesia. 

Merge `patient_post_op_complications` `patient_information`, `patient_labs` and `patient_procedure_events` by the unique identifiers `LOG_ID` and `MRN`. 

**Feature engineering**
1. Convert the outcome to binary 0/1.
2. Create `BMI` variable based on height and weight (`HEIGHT` and `WEIGHT` variables should have the desired units and with no missing values by this step).
3. Create time stamp for when the lastest available preoperative lab test occurred
    - For each encounter (unique `MRN, LOG_ID` combination), find only the most recent `Collection Datetime` (from `patient_labs`) before `AN_START_DATETIME` (from `patient_information`).
    - Retain also the corresponding lab test name and measurements for that specific test.
4. (Optional) Get the name for the specific anesthesia procedure by mapping `AN_START_DATETIME` to `EVENT_TIME` (from `patient_procedure_events`).